[package]
name = "elm-test-rs"
version = "0.1.0"
authors = ["Matthieu Pizenberg <matthieu.pizenberg@gmail.com>", "Harry Sarson <harry.sarson@hotmail.co.uk>"]
edition = "2018"
description = "Simple and fast rust alternative to node-test-runner for elm-test"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pico-args = "0.3.4"
glob = "0.3.0"
pathdiff = "0.2.0"
num_cpus = "1.13.0"
tree-sitter = "0.17.0"
regex = "1.4.1"
lazy_static = "1.4.0"
tree-sitter-elm = "4.3.4"
# pubgrub-dependency-provider-elm = { path = "../pubgrub-dependency-provider-elm" }
pubgrub-dependency-provider-elm = { git = "https://github.com/mpizenberg/pubgrub-dependency-provider-elm", branch = "master" }
serde_json = "1.0.59"
ureq = "1.5.2"
dirs = "3.0.1"
pubgrub = { version = "0.2", features = ["serde"] }

[dev-dependencies]

[build-dependencies]
fs_extra = "1.2.0"
dirs = "3.0.1"
