[package]
name = "elm-test-rs"
version = "0.1.0"
authors = ["Matthieu Pizenberg <matthieu.pizenberg@gmail.com>"]
edition = "2018"
description = "Simple and fast rust alternative to node-test-runner for elm-test"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pico-args = "0.3.1"
glob = "0.3.0"
varj = "0.1.0"
miniserde = "0.1"
pathdiff = "0.1"
rand = { version = "0.7.3", default-features = false, features = ["std"] }
num_cpus = "1"
thiserror = "1.0.21"
tree-sitter = "0.17.0"
regex = "1.4.1"
lazy_static = "1.4.0"
tree-sitter-elm = "4.3.4"

[dev-dependencies]

[build-dependencies]
cc="1"

