name: CI

on:
  push:
    branches:
      - staging
      - trying

  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: rust:alpine
    steps:
      - name: Install git
        run: apk add git musl-dev g++

      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Download cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ hashFiles('Cargo.toml') }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('Cargo.toml') }}
            ${{ runner.os }}

      - name: Build
        run: cargo build --verbose --release

      - uses: actions/upload-artifact@v2
        with:
          name: elm-test-rs
          path: target/release/elm-test-rs

  # test:
  #   name: Test
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       os:
  #         - ubuntu-latest
  #         - windows-latest
  #         - macos-latest
  #       rust:
  #         - stable
  #         - beta
  #         - nightly
  #
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         submodules: recursive
  #
  #     - uses: actions-rs/toolchain@v1
  #       with:
  #         profile: minimal
  #         toolchain: ${{ matrix.rust }}
  #         override: true
  #         components: rustfmt, clippy
  #
  #     - uses: actions-rs/cargo@v1
  #       with:
  #         command: build
  #
  #     - uses: actions-rs/cargo@v1
  #       with:
  #         command: fmt
  #         args: --all -- --check
  #
  #     - uses: actions-rs/cargo@v1
  #       with:
  #         command: clippy
  #         args: --all
